### ISSUE TITLE
Support Other Slack Compatible Tools

### ISSUE THREAD

**Issue by graywolf336** [jacted/speed-monitor#2]
Would be nice to have support for other team communication tools which have Slack support, such as Rocket.Chat and Mattermost (both are open source).

**Comment by jacted** [comment]
Great idea.

Im looking into this.

**Comment by jacted** [comment]
I made a commit with the Rocket.chat integration: https://github.com/jacted/speed-monitor/commit/bce6b9b0e272732c1a36ba4f2b6b5ecdb0b23091

I will try to look into Mattermost aswell.

**Comment by graywolf336** [comment]
I'll take a look, but you might want to look into webhooks since I believe
all three support the same format and that'd simplify your code.

**Comment by jacted** [comment]
Yep, i am converting slack into outgoing webhook right now aswell.

**Comment by jacted** [comment]
I cleaned up the code so now its only one file handling the webhooks (https://github.com/jacted/speed-monitor/commit/ff56dd9e37566d16d6f265968c6fa55f419bbf52)

Slack, Rocket.chat & Mattermost is supported now. Let me know what you think.

**Comment by jacted** [comment]
I am closing this issue. Feel free to reopen if there is any errors or its not working.
