### ISSUE TITLE
Multiple domain support

### ISSUE THREAD

**Issue by designfrontier** [jacted/speed-monitor#3]
Add support for multiple domains... 

//note: mostly creating this here because I am interested in the future and curious what it would look like. And so that it can get fleshed out enough for someone like me to implement and PR it. If this isn't cool feel free to close it 😄

**Comment by jacted** [comment]
Hi Daniel, thanks for your interest.

I'm actually already working on it. It's only a small change.

The config will be changed a bit to look like this.
```javascript
domains: [
    {
        alias: 'localhost',
        domain: 'localhost.com'
    },
    {
        alias: 'mywebsite',
        domain: 'mywebsite.com'
    }
]
```

Then to get stats you would have to use: `speed report mywebsite` or `speed report full mywebsite`

**Comment by jacted** [comment]
I commited the change https://github.com/jacted/speed-monitor/commit/23df7ff84debc42eab1b8f8ee52ac408825021dd

I am closing this issue.
